"""Shared utilities for Karter template tools."""

from .prompts import load_prompt
from .providers import (
    PROVIDERS,
    create_client,
    get_api_key,
    load_env,
    save_env,
    select_model,
    select_provider,
)
from .ui import (
    BACK,
    STYLE_ACCENT,
    STYLE_ERROR,
    STYLE_OK,
    STYLE_TITLE,
    ask,
    ask_line,
    confirm,
    confirm2,
    console,
    make_progress,
    pick_multi,
    pick_option,
    print_header,
    print_title,
    read_key,
    run_cli,
    select,
    select_path,
    style,
)

__all__ = [
    "BACK",
    "PROVIDERS",
    "STYLE_ACCENT",
    "STYLE_ERROR",
    "STYLE_OK",
    "STYLE_TITLE",
    "ask",
    "ask_line",
    "confirm",
    "confirm2",
    "console",
    "create_client",
    "get_api_key",
    "load_env",
    "load_prompt",
    "make_progress",
    "pick_multi",
    "pick_option",
    "print_header",
    "print_title",
    "read_key",
    "run_cli",
    "save_env",
    "select",
    "select_model",
    "select_path",
    "select_provider",
    "style",
]